Ensure git safe dir comes after checkout
There were some cases where the step was missing and
others where it came after fetching additional references.

diff --git a/.github/workflows/container-builds-packages.yml b/.github/workflows/container-builds-packages.yml
--- a/.github/workflows/container-builds-packages.yml
+++ b/.github/workflows/container-builds-packages.yml
@@ -62,6 +62,17 @@ jobs:
           fetch-depth: ${{ inputs.fetch-depth }}
           fetch-tags: true
 
+      # Mark the current working directory as a safe directory in git to
+      # resolve "dubious ownership" complaints.
+      #
+      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
+      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
+      # https://github.com/actions/runner-images/issues/6775
+      # https://github.com/actions/checkout/issues/766
+      - name: Mark the current working directory as a safe directory in git
+        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
+        run: git config --global --add safe.directory "${PWD}"
+
       - name: Fetch additional references
         if: ${{ github.event_name == 'pull_request' }}
         run: |
@@ -107,14 +118,6 @@ jobs:
           fetch-depth: ${{ inputs.fetch-depth }}
           fetch-tags: true
 
-      - name: Fetch additional references
-        if: ${{ github.event_name == 'pull_request' }}
-        run: |
-          git fetch origin ${{ inputs.primary-branch }} --depth ${{ inputs.fetch-depth }}
-
-          # Allow fetch attempts for ${{ inputs.development-branch }} to fail
-          git fetch origin ${{ inputs.development-branch }} --depth ${{ inputs.fetch-depth }} || true
-
       # Mark the current working directory as a safe directory in git to
       # resolve "dubious ownership" complaints.
       #
@@ -125,6 +128,14 @@ jobs:
       - name: Mark the current working directory as a safe directory in git
         # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
         run: git config --global --add safe.directory "${PWD}"
+
+      - name: Fetch additional references
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          git fetch origin ${{ inputs.primary-branch }} --depth ${{ inputs.fetch-depth }}
+
+          # Allow fetch attempts for ${{ inputs.development-branch }} to fail
+          git fetch origin ${{ inputs.development-branch }} --depth ${{ inputs.fetch-depth }} || true
 
       - name: Build packages
         run: make packages
diff --git a/.github/workflows/container-builds-release.yml b/.github/workflows/container-builds-release.yml
--- a/.github/workflows/container-builds-release.yml
+++ b/.github/workflows/container-builds-release.yml
@@ -58,6 +58,17 @@ jobs:
         with:
           fetch-depth: ${{ inputs.fetch-depth }}
 
+      # Mark the current working directory as a safe directory in git to
+      # resolve "dubious ownership" complaints.
+      #
+      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
+      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
+      # https://github.com/actions/runner-images/issues/6775
+      # https://github.com/actions/checkout/issues/766
+      - name: Mark the current working directory as a safe directory in git
+        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
+        run: git config --global --add safe.directory "${PWD}"
+
       - name: Fetch additional references
         if: ${{ github.event_name == 'pull_request' }}
         run: |
@@ -92,14 +103,6 @@ jobs:
           fetch-depth: ${{ inputs.fetch-depth }}
           fetch-tags: true
 
-      - name: Fetch additional references
-        if: ${{ github.event_name == 'pull_request' }}
-        run: |
-          git fetch origin ${{ inputs.primary-branch }} --depth ${{ inputs.fetch-depth }}
-
-          # Allow fetch attempts for ${{ inputs.development-branch }} to fail
-          git fetch origin ${{ inputs.development-branch }} --depth ${{ inputs.fetch-depth }} || true
-
       # Mark the current working directory as a safe directory in git to
       # resolve "dubious ownership" complaints.
       #
@@ -110,6 +113,14 @@ jobs:
       - name: Mark the current working directory as a safe directory in git
         # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
         run: git config --global --add safe.directory "${PWD}"
+
+      - name: Fetch additional references
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          git fetch origin ${{ inputs.primary-branch }} --depth ${{ inputs.fetch-depth }}
+
+          # Allow fetch attempts for ${{ inputs.development-branch }} to fail
+          git fetch origin ${{ inputs.development-branch }} --depth ${{ inputs.fetch-depth }} || true
 
       - name: Use Podman to generate release build assets
         run: make podman-release-build
diff --git a/.github/workflows/release-build.yml b/.github/workflows/release-build.yml
--- a/.github/workflows/release-build.yml
+++ b/.github/workflows/release-build.yml
@@ -118,15 +118,6 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v3.6.0
 
-      # Additional references are needed for choffmeister/git-describe-semver
-      # to successfully generate a release version based on git history.
-      - name: Fetch additional references
-        run: |
-          git fetch origin ${{ inputs.primary-branch }} --depth ${{ inputs.fetch-depth }}
-
-          # Allow fetch attempts for ${{ inputs.development-branch }} to fail
-          git fetch origin ${{ inputs.development-branch }} --depth ${{ inputs.fetch-depth }} || true
-
       # Mark the current working directory as a safe directory in git to
       # resolve "dubious ownership" complaints.
       #
@@ -137,6 +128,15 @@ jobs:
       - name: Mark the current working directory as a safe directory in git
         # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
         run: git config --global --add safe.directory "${PWD}"
+
+      # Additional references are needed for choffmeister/git-describe-semver
+      # to successfully generate a release version based on git history.
+      - name: Fetch additional references
+        run: |
+          git fetch origin ${{ inputs.primary-branch }} --depth ${{ inputs.fetch-depth }}
+
+          # Allow fetch attempts for ${{ inputs.development-branch }} to fail
+          git fetch origin ${{ inputs.development-branch }} --depth ${{ inputs.fetch-depth }} || true
 
       - name: Use Podman to generate release build assets
         if: ${{ inputs.generate-assets }}
